spring:
  # Kafka main Settings
  kafka:
    topic:
      name: "order_topic"
    # Consumer Configuration
    consumer:
      enable-auto-commit: true
      bootstrap-servers: localhost:9092
      group-id: EventDrivenMicrcroservice
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      max-pollrecords: 2000
      fetch-min-size: 262144
      fetch-max-wait: 100
      heartbeat-interval: 7000
      properties:
        spring:
          json:
            trusted:
              packages: '*'
        spring.json.value.default.type: com.fasterxml.jackson.databind.JsonNode
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

  application:
    name: stock-service
server:
  port: '8081'