spring:
  # Kafka main Settings
  kafka:
    topic:
      name: "order_topic"
    # producer Configuration
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        linger.ms: 50 #  the amount of time to wait for additional messages before sending current batch.
        batch.size: 20000 # The maximum amount of data that can be sent in a single request
        delivery.timeout.ms: 90100
        buffer.memory: 67008864 #  if broker is down, it starts accumulating the message batches in buffer memory (D:32MB).

  application:
    name: order-service
server:
  port: '8080'